version: '3'

services:
  node:
    container_name: ${STAGE}-${BUILD_TAG}-node
    image: node:12-alpine
    env_file:
      - .env
    volumes:
      - .:/usr/app
    network_mode: host
    restart: always
    working_dir: /usr/app
    command: sh -c "npm install && npm run serve"